kind: pipeline
type: docker
name: main

steps:
  - name: build
    image: golang
    commands:
      - go build
      - echo "main"
trigger:
  branch:
    - main

---

kind: pipeline
type: docker
name: develop

steps:
  - name: build
    image: golang
    commands:
      - go build
      - echo "develop"
trigger:
  branch:
    - develop